name: CD - Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull latest code
        run: |
          cd ~/projects/tum-web-lab2
          git fetch origin
          git reset --hard origin/master

      - name: Rebuild and restart containers
        run: |
          cd ~/projects/tum-web-lab2
          docker compose up --build -d
          docker image prune -f
